[package]
name = "jot2"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "*", features = ["serde"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
thiserror = "*"
dirs = "*"
clap = { version = "*", features = ["derive"] }
tempfile = "3.13.0"
colored = "*"
